name: xgboost_training
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas>=1.5.0
  - numpy>=1.23.0
  - scikit-learn>=1.2.0
  - xgboost>=2.0.0
  - optuna>=3.0.0
  - pip
  - pip:
    - rdkit-pypi>=2022.9.5
    - mordred>=1.2.0
    - map4>=0.1.0

